const translateArr = {
    'author-p' : {
        'ru':'Автор: Вадим Вердож',
        'en':'Author: Vadim Verdoj',
        'fr':'Auteur : Vadim Verdozh',
        'ita':'Autore: Vadim Verdozh',
        'jap':'著者: ヴァディム・ヴェルドージ',
    },
    'instruction-btn':{
        'ru':'Как с этим работать?',
        'en':'How to work with this?',
        'fr':'Comment travailler avec ça ?',
        'ita':'Come lavorare con questo?',
        'jap':'これをどうやって扱えばいいのでしょうか?',
    },
    'button-title':{
        'ru':'Старт',
        'en':'Start',
        'fr':'Commencer',
        'ita':'Inizio',
        'jap':'始める',
    },
    'purpose-h':{
        'ru':'Этот сайт сделан для создания "плавающих" окон из вкладок браузера, окон или целых экранов вашего компьютера',
        'en':'This site is made to create "floating" windows from browser tabs, windows or entire screens of your computer',
        'fr':'Ce site est conçu pour créer des fenêtres \« flottantes \» à partir d\'onglets de navigateur, de fenêtres ou d\'écrans entiers de votre ordinateur',
        'ita':'Questo sito è stato creato per creare finestre "mobili" da schede del browser, finestre o intere schermate del computer',
        'jap':'このサイトは、ブラウザのタブ、ウィンドウ、またはコンピュータの画面全体から「フローティング」ウィンドウを作成するために作られています。',
    },
    'warning-p':{
        'ru':'Важно: для корректной работы используйте ПК версию сайта',
        'en':'Warning: for correct operation please use the PC version of the site',
        'fr':'Important : pour un fonctionnement correct veuillez utiliser la version PC du site',
        'ita':'Importante: per un corretto funzionamento utilizzare la versione PC del sito',
        // 'jap':'重要: 正しく操作するには、サイトのPC版をご利用ください。',
    },
    'instruction-h':{
        'ru':'ИНСТРУКЦИЯ',
        'en':'INSTRUCTIONS',
        'fr':'INSTRUCTIONS',
        'ita':'ISTRUZIONI',
        'jap':'説明書',
    },
    'first-step':{
        'ru':'1. Нажмите на большую красную кнопку (ее трудно не заметить)',
        'en':'1. Press the big red button (it\'s hard to miss)',
        'fr':'1. Appuyez sur le gros bouton rouge (difficile à manquer)',
        'ita':'1. Premere il grande pulsante rosso (è difficile non vederlo)',
        'jap':'1. 大きな赤いボタンを押します（見逃しにくいです）',
    },
    'second-step':{
        'ru':'2. Ориентируясь в этом меню, выберите, что хотите открыть как плавающее окно',
        'en':'2. Using this menu, select what you want to open as a floating window.',
        'fr':'2. À l’aide de ce menu, sélectionnez ce que vous souhaitez ouvrir comme fenêtre flottante.',
        'ita':'2. Utilizzando questo menu, seleziona ciò che desideri aprire come finestra mobile.',
        'jap':'2. このメニューを使用して、フローティング ウィンドウとして開くものを選択します。',
    },
    'third-step':{
        'ru':'3. Нажмите "Поделиться"',
        'en':'3. Click left button',
        'fr':'3. Appuyez sur le bouton gauche',
        'ita':'3. Premere il pulsante sinistro',
        'jap':'3. 左ボタンを押す',
    },
    'forth-step':{
        'ru':'4. Если вы выбрали вкладку браузера, то жмите на "Перейти на вкладку: floatingpicturee.netlify.app"',
        'en':'4. If you have selected a browser tab, then click on "Go to tab: floatingpicturee.netlify.app"',
        'fr':'4. Si vous avez sélectionné un onglet de navigateur, cliquez sur « Aller à l\'onglet : floatingpicturee.netlify.app »',
        'ita':'4. Se hai selezionato una scheda del browser, clicca su "Vai alla scheda: floatingpicturee.netlify.app"',
        'jap':'4. ブラウザタブを選択した場合は、「タブに移動: floatingpicturee.netlify.app」をクリックします。',
    },
    'finish-page-h':{
        'ru':'Стоковые люди показывают большой палец',
        'en':'Stock people giving thumbs up',
        'fr':'Les gens de la bourse lèvent le pouce',
        'ita':'Persone che fanno il pollice in su',
        'jap':'親指を立てているストックの人々',
    },
}